### PR TITLE
Ensure tableName is always SQL-safe

### LINKED ISSUE #69: Validate ECK entity type names for creating valid MySQL table names - DB Error: Syntax error when upgrading CiviCRM Core - dropping triggers
When upgrading CiviCRM Core from 5.58 to 5.61, I got this error thrown:

`DROP TRIGGER IF EXISTS civicrm_eck_-extension_before_insert [nativecode=1064 ** You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-extension_before_insert' at line 1]`

Seems `-` is not allowed in trigger names, but the ECK entity table contains one.

### PR DESCRIPTION
**Pull request by colemanw**
Fixes #69

### CODE REVIEW

File: eck.php [hunk 1]
```diff
@@ -26,6 +26,17 @@ function eck_civicrm_config(&$config) {
...
+/**
+ * Convert ECK EntityType name to sql table name.
+ *
+ * @param string $entityTypeName
+ * @return string
+ */
+function _eck_get_table_name(string $entityTypeName): string {
+  // SQL table names must be alphanumeric and no longer than 64 characters
+  return CRM_Utils_String::munge('civicrm_eck_' . strtolower($entityTypeName), '_', 64);
+}
```
Comment (jensschuppe) [inline eck.php:38]: We're currently not validating name collisions, do we; shall we?

Comment (colemanw) [reply eck.php:38]: Yes we do. There is a unique index on `EntityType.name`:

https://github.com/systopia/de.systopia.eck/blob/a6cb9b58d59ff12a644d928477da8f2524fa540e/xml/schema/CRM/Eck/EckEntityType.xml#L36-L40

Comment (colemanw) [reply eck.php:38]: @jensschuppe `EntityType.name` has enforced uniqueness at the DB level, however it has a maxlength of 255 which then would get trimmed by this function to `64 - strlen('civicrm_eck_')` which is 58 characters. So in theory any entities beginning with the same 58 characters could cause name collisions with identical db table names.
I think we ought to reduce the length of the `name` column to 58 characters. I can do that in a followup PR after you merge this.
